set_property PACKAGE_PIN AA13 [get_ports {btns[0]}]
set_property PACKAGE_PIN AE14 [get_ports {btns[1]}]
set_property PACKAGE_PIN AE15 [get_ports {btns[2]}]
set_property PACKAGE_PIN AG14 [get_ports {btns[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns[*]}]

set_property PACKAGE_PIN W13	 [get_ports {leds[0]}]
set_property PACKAGE_PIN Y12	 [get_ports {leds[1]}]
set_property PACKAGE_PIN AA12 [get_ports {leds[2]}]
set_property PACKAGE_PIN AB13 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[*]}]
